# Generated by Django 3.2.19 on 2025-02-18 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_agency_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agency',
            options={},
        ),
        migrations.RenameField(
            model_name='bus',
            old_name='available',
            new_name='is_full',
        ),
        migrations.AddField(
            model_name='agency',
            name='address',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agency',
            name='phone',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bus',
            name='bus_number',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bus',
            name='sits',
            field=models.IntegerField(default=70),
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('code', models.CharField(max_length=50)),
                ('transaction_id', models.IntegerField()),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.bus')),
            ],
        ),
    ]
