# Generated by Django 3.2.19 on 2025-02-18 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_bus_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='ticktet_holder_first_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tickets',
            name='ticktet_holder_last_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
