# Generated by Django 3.2.19 on 2025-02-18 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20250218_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busschedule',
            name='bus',
        ),
        migrations.RemoveField(
            model_name='busschedule',
            name='bus_route',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='agency',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='bus',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='bus_schedule',
        ),
        migrations.AddField(
            model_name='bus',
            name='route',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tickets',
            name='bus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.bus'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bus',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.DeleteModel(
            name='BusRoutes',
        ),
        migrations.DeleteModel(
            name='BusSchedule',
        ),
        migrations.DeleteModel(
            name='payment',
        ),
    ]
