# Generated by Django 3.2.19 on 2025-02-18 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20250218_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='payment_status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
