# Generated by Django 3.2.19 on 2025-02-27 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20250227_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='sits_available',
            field=models.IntegerField(default=70),
        ),
        migrations.AddField(
            model_name='tickets',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tickets',
            name='phone',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bus',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=50)),
                ('is_booked', models.BooleanField(default=False)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.bus')),
            ],
        ),
        migrations.AddField(
            model_name='tickets',
            name='seat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.seat'),
            preserve_default=False,
        ),
    ]
