# Generated by Django 3.2.19 on 2025-02-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_auto_20250227_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='seat_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='tickets',
            unique_together={('bus', 'seat_number')},
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='seat',
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
    ]
