# Generated by Django 3.2.19 on 2025-02-28 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickets',
            old_name='user',
            new_name='ticket_user',
        ),
    ]
