# Generated by Django 3.2.19 on 2025-02-28 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_rename_user_tickets_ticket_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickets',
            old_name='ticket_user',
            new_name='user',
        ),
        migrations.AddField(
            model_name='agency',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.user'),
            preserve_default=False,
        ),
    ]
