# Generated by Django 3.2.19 on 2025-02-28 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_auto_20250228_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='user',
        ),
    ]
