# Generated by Django 3.2.19 on 2025-02-28 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_auto_20250228_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.user'),
            preserve_default=False,
        ),
    ]
