# Generated by Django 3.2.19 on 2025-02-28 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_tickets_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='user',
        ),
    ]
